apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencart
  # Add labels to your application object.
  labels:
    name: opencart
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # The project the application belongs to.
  project: {{.Release.Namespace}}

  # Source of the application manifests
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Can point to either a Helm chart repo or a git repo.
    targetRevision: 13.0.8  # For Helm, this refers to the chart version.
    chart: opencart  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

    helm:
      # Release name override (defaults to application name)
      releaseName: opencart
      version: v3
      values: |
        opencartPassword: randomPassword
        resources:
          requests:
            memory: "300Mi"
            cpu: "150m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        service:
          type: ClusterIP
        podAnnotations:
          sidecar.istio.io/inject: "true"
        podLabels:
          findi.io/env: prod
        persistence:
          enabled: true
          size: 1Gi
        mariadb:
          enabled: false
        externalDatabase:
          host: maxscale.{{.Release.Namespace}}.svc.cluster.local
          port: 3306
          user: bn_opencart
          password: randomPassword
          database: bitnami_opencart
        ingress:
          enabled: true
          hostname: opencart.{{.Release.Namespace}}.findi.biz
          tls: false
          annotations:
            external-dns: "true"
            nginx.ingress.kubernetes.io/service-upstream: "true"
            nginx.ingress.kubernetes.io/upstream-vhost: "opencart.{{.Release.Namespace}}.svc.cluster.local"
        extraDeploy:
          - |
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              labels:
                app.kubernetes.io/instance: opencart
                app.kubernetes.io/name: opencart

              name: opencart-opencart-test
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
          - |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              labels:
                app.kubernetes.io/instance: opencart
                app.kubernetes.io/name: opencart
              name: opencart-test
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app.kubernetes.io/instance: opencart
                  app.kubernetes.io/name: opencart
              template:
                metadata:
                  annotations:
                    prometheus.io/port: "9117"
                    prometheus.io/scrape: "true"
                    sidecar.istio.io/inject: "true"
                    traffic.sidecar.istio.io/excludeOutboundPorts: "3307"
                  labels:
                    app.kubernetes.io/instance: opencart
                    app.kubernetes.io/name: opencart
                    findi.io/env: test
                spec:
                  containers:
                  - env:
                    - name: BITNAMI_DEBUG
                      value: "false"
                    - name: ALLOW_EMPTY_PASSWORD
                      value: "yes"
                    - name: APACHE_HTTP_PORT_NUMBER
                      value: "8080"
                    - name: APACHE_HTTPS_PORT_NUMBER
                      value: "8443"
                    - name: OPENCART_DATABASE_HOST
                      value: maxscale.{{.Release.Namespace}}.svc.cluster.local
                    - name: OPENCART_DATABASE_PORT_NUMBER
                      value: "3307"
                    - name: OPENCART_DATABASE_NAME
                      value: bitnami_opencart
                    - name: OPENCART_DATABASE_USER
                      value: bn_opencart
                    - name: OPENCART_DATABASE_PASSWORD
                      value: "randomPassword"
                    - name: OPENCART_SKIP_BOOTSTRAP
                      value: "no"
                    - name: OPENCART_HOST
                      value: opencart.{{.Release.Namespace}}.findi.biz
                    - name: OPENCART_USERNAME
                      value: user
                    - name: OPENCART_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: opencart-password
                          name: opencart
                    - name: OPENCART_EMAIL
                      value: user@example.com
                    image: docker.io/bitnami/opencart:4.0.1-1-debian-11-r52
                    imagePullPolicy: IfNotPresent
                    livenessProbe:
                      failureThreshold: 6
                      httpGet:
                        httpHeaders:
                        - name: Host
                          value: opencart.{{.Release.Namespace}}.findi.biz
                        path: /administration/
                        port: http
                        scheme: HTTP
                      initialDelaySeconds: 120
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 5
                    name: opencart
                    ports:
                    - containerPort: 8080
                      name: http
                      protocol: TCP
                    - containerPort: 8443
                      name: https
                      protocol: TCP
                    readinessProbe:
                      failureThreshold: 6
                      httpGet:
                        httpHeaders:
                        - name: Host
                          value: opencart.{{.Release.Namespace}}.findi.biz
                        path: /administration/
                        port: http
                        scheme: HTTP
                      initialDelaySeconds: 30
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 3
                    resources:
                      limits:
                        cpu: 500m
                        memory: 1Gi
                      requests:
                        cpu: 150m
                        memory: 300Mi
                    securityContext:
                      runAsNonRoot: true
                      runAsUser: 1001
                    volumeMounts:
                    - mountPath: /bitnami/opencart
                      name: opencart-data
                      subPath: opencart
                    - mountPath: /bitnami/opencart_storage
                      name: opencart-data
                      subPath: opencart_storage
                  restartPolicy: Always
                  schedulerName: default-scheduler
                  securityContext:
                    fsGroup: 1001
                  terminationGracePeriodSeconds: 30
                  volumes:
                  - name: opencart-data
                    persistentVolumeClaim:
                      claimName: opencart-opencart-test
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: {{.Release.Namespace}}

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=false # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    # The retry feature is available since v1.7
    - RespectIgnoreDifferences=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process.
  ignoreDifferences:
  # for the specified json pointers
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: Statefulset
    jsonPointers:
    - /spec/replicas
  # for the specified managedFields managers
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager
  - group: "*"
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
