tracking:
  token: 12078e6dafa7484b11978f76fdc8726b
ghost:
  host: ghost.test.svc.cluster.local
matomo:
  host: matomo.test.svc.cluster.local
  port: 80
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health"
