tracking:
  token: 4b403e684c697dfe289752ca145caddc
ghost:
  endpoint: http://ghost.test.svc.cluster.local:80
matomo:
  host: matomo.test.svc.cluster.local
  port: 80
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health"