---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matomo
  # Add labels to your application object.
  labels:
    name: matomo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # The project the application belongs to.
  project: {{.Release.Namespace}}

  # Source of the application manifests
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Can point to either a Helm chart repo or a git repo.
    targetRevision: 0.2.17  # For Helm, this refers to the chart version.
    chart: matomo  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

    helm:
      passCredentials: false # If true then adds --pass-credentials to Helm commands to pass credentials to all domains
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)

      # Release name override (defaults to application name)
      releaseName: matomo
      version: v3
      values: |
        customPostInitScripts:
          custom_init_script.sql: |
            INSERT INTO `matomo_user_token_auth` (`idusertokenauth`,`login`,`description`,`password`,`hash_algo`,`system_token`,`last_used`,`date_created`,`date_expired`) VALUES (2,'demo','anonymous default token','53660be1f5b2415945a18904e59b5347325748001087fac69f9a28d62e3f4a4721f4093c1bc82e9675884bf468f70ae3a2d5224b2c551f6b0927fa8d3edf2e74','sha512',0,'2023-01-30 18:49:59','2023-01-30 18:49:55',NULL);
        matomoUsername: demo
        matomoPassword: randomPassword
        matomoEmail: demo.user@test.com
        matomoWebsiteName: Ghost
        matomoWebsiteHost: http://ghost.{{.Release.Namespace}}.findi.biz
        allowEmptyPassword: false
        matomoSkipInstall: false
        containerSecurityContext:
          runAsNonRoot: false
        service:
          type: ClusterIP
        replicaCount: 1
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "400m"
        podAnnotations:
          sidecar.istio.io/inject: "false"
        persistence:
          enabled: false
        mariadb:
          enabled: false
        externalDatabase:
          host: maxscale.{{.Release.Namespace}}.svc.cluster.local
          user: ghost
          password: randomPassword
          database: ghost
        ingress:
          enabled: true
          hostname: matomo.{{.Release.Namespace}}.findi.biz
          tls: false
          annotations:
            external-dns: "true"
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: {{.Release.Namespace}}


  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=false # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    # The retry feature is available since v1.7
    - RespectIgnoreDifferences=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process.
  ignoreDifferences:
  # for the specified json pointers
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: Statefulset
    jsonPointers:
    - /spec/replicas
  # for the specified managedFields managers
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager
  - group: "*"
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
