apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-config
data:
  config.production.json: |
    {
      "database": {
        "client": "mysql",
        "connection": {
          "host": "maxscale.{{.Release.Namespace}}.svc.cluster.local",
          "port": 3306,
          "database": "ghost",
          "user": "ghost",
          "password": "randomPassword",
          "ssl": false
        },
        "pool": {
          "min": 0,
          "max": 20
        }
      },
      "url": "http://ghost.{{.Release.Namespace}}.findi.biz/",
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "mail": {
        "transport": "SMTP",
        "from": "demo.user@test.com",
        "options": {
          "host": "smtp4dev.{{.Release.Namespace}}.svc.cluster.local",
          "port": 25,
          "secureConnection": false,
          "auth": {
            "user": "postmaster",
            "pass": "mailpassword"
          }
        }
      },
      "logging": {
        "level": "debug",
        "transports": [
          "stdout",
          "file"
        ]
      },
      "process": "local",
      "paths": {
        "contentPath": "/bitnami/ghost/content/"
      }
    }
