apiVersion: v1
kind: Service
metadata:
  name: maxscale
spec:
  selector:
    app: maxscale
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: http
      protocol: TCP
      port: 8989
      targetPort: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxscale
  labels:
    app: maxscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxscale
  template:
    metadata:
      labels:
        app: maxscale
    spec:
      containers:
        - name: maxscale
          image: mariadb/maxscale:22.08.2
          ports:
            - containerPort: 8989
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
          volumeMounts:
            - mountPath: /etc/maxscale.cnf
              name: maxscale-config
              subPath: mariadb-maxscale.cnf
            - mountPath: /var/log/maxscale
              name: log
      volumes:
        - emptyDir: {}
          name: log
        - configMap:
            defaultMode: 420
            name: maxscale-config
          name: maxscale-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maxscale-ingress
  annotations:
    external-dns: "true"
spec:
  rules:
  - host: maxscale.{{.Release.Namespace}}.findi.biz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maxscale
            port:
              number: 8989
